[metadata]
name = fastfields
author = Yael Balbastre
author_email = yael.balbastre@gmail.com
description = Fast PyTorch tools for dense scalar and vector fields (implemented in C++/CUDA)
long_description = file:README.md
version = attr: fastfields.__version__
platforms = OS Independent
license = MIT
license_files = LICENSE
classifiers =
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent
    Programming Language :: Python :: 3
    Intended Audience :: Science/Research
    Topic :: Scientific/Engineering :: Artificial Intelligence
    Topic :: Scientific/Engineering :: Medical Science Apps.
project_urls =
    Source Code=https://github.com/balbasty/fastfields

[options]
python_requires = >= 3.6
install_requires =
    torch >= 1.4
    numpy
    scipy
