name: manual-build-wheels

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Operating system'
        required: false
        default: 'ubuntu-18.04'
      python-version:
        description: 'Version of python'
        required: false
        default: '3.8'
      pytorch-version:
        description: 'Version of pytorch'
        required: false
        default: 'latest'
      cuda-version:
        description: 'Version of cuda'
        required: false
        default: '10.2'
      ff-version:
        description: 'Target version'
        required: false
        default: ''
      publish:
        description: 'Publish to GemFury'
        required: false
        default: 'false'
      upload-artifact:
        description: 'Upload artifact'
        required: false
        default: 'false'

jobs:
  build_wheels:
    env:
      OS: ${{ github.event.inputs.os }}
      PYTHON: ${{ github.event.inputs.python-version }}
      PYTORCH: ${{ github.event.inputs.pytorch-version }}
      CUDA: ${{ github.event.inputs.cuda-version }}
      FF_VERSION: ${{ github.event.inputs.ff-version }}

    name: Build wheel for os=${{ github.event.inputs.os }}
          python=${{ github.event.inputs.python-version }}
          torch=${{ github.event.inputs.pytorch-version }}
          cuda=${{ github.event.inputs.cuda-version }}
    runs-on: ${{ github.event.inputs.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up conda with Python ${{ github.event.inputs.python-version }}
        uses: s-weigand/setup-conda@v1
        with:
          python-version: ${{ env.PYTHON }}
          conda-channels: pytorch

      - if: runner.os == 'macOS'
        run: echo "CUDA=cpu" >> $GITHUB_ENV
      - if: ${{ env.CUDA == 8.0 }}
        run: echo "CUDA=8.0.61" >> $GITHUB_ENV
      - if: ${{ env.CUDA == 8.0 }}
        run: echo "CUDA=8.0.61" >> $GITHUB_ENV
      - if: ${{ env.CUDA == 9.2 }}
        run: echo "CUDA=9.2.148" >> $GITHUB_ENV
      - if: ${{ env.CUDA == 10.0 }}
        run: echo "CUDA=10.0.130" >> $GITHUB_ENV
      - if: ${{ env.CUDA == 10.1 }}
        run: echo "CUDA=10.1.243" >> $GITHUB_ENV
      - if: ${{ env.CUDA == 10.2 }}
        run: echo "CUDA=10.2.89" >> $GITHUB_ENV
      - if: ${{ env.CUDA == 11.0 }}
        run: echo "CUDA=11.0.3" >> $GITHUB_ENV
      - if: ${{ env.CUDA == 11.1 }}
        run: echo "CUDA=11.1.1" >> $GITHUB_ENV
      - if: ${{ env.CUDA == 11.2 }}
        run: echo "CUDA=11.2.2" >> $GITHUB_ENV
      - if: ${{ env.CUDA == 11.3 }}
        run: echo "CUDA=11.3.1" >> $GITHUB_ENV
      - if: ${{ env.CUDA == 11.4 }}
        run: echo "CUDA=11.4.3" >> $GITHUB_ENV
      - if: ${{ env.CUDA == 11.5 }}
        run: echo "CUDA=11.5.2" >> $GITHUB_ENV
      - if: ${{ env.CUDA == 11.6 }}
        run: echo "CUDA=11.6.2" >> $GITHUB_ENV
      - if: ${{ env.CUDA == 11.7 }}
        run: echo "CUDA=11.7.0" >> $GITHUB_ENV

      - name: Setup CUDA Toolkit ${{ github.event.inputs.cuda-version }}
        if: ${{ env.CUDA }} != 'cpu'
        id: install-cuda-base
        uses: Jimver/cuda-toolkit@v0.2.8
        with:
          cuda: ${{ env.CUDA }}
          linux-local-args: '["--toolkit"]'

      - name: Setup conda env with PyTorch ${{ github.event.inputs.pytorch-version }} + CUDA ${{ github.event.inputs.cuda-version }}
        if: ${{ env.CUDA }} != 'cpu'
        run: conda install -y "pytorch=$PYTORCH" "cudatoolkit=$CUDA"

      - name: Setup conda env with PyTorch ${{ github.event.inputs.pytorch-version }} for CPU
        if: ${{ env.CUDA }} == 'cpu'
        run: conda install -y "pytorch=$PYTORCH" cpuonly

      - name: Build wheel
        env:
          FF_CUDA_ARCH_LIST: all
        run: |
          [ "$CUDA" == "cpu" ] && export FF_USE_CUDA="0" || export FF_USE_CUDA="1"
          python setup.py bdist_wheel

      - name: Upload artifact
        if: github.event.inputs.upload-artifact == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: wheel-ff${{env.FF_VERSION}}-pytorch${{env.PYTORCH}}-cuda${{env.CUDA}}-python${{env.PYTHON}}-${{env.OS}}
          path: dist/*.whl

      - name: Publish wheels
        if: github.event.inputs.publish == 'true'
        env:
          TOKEN: ${{ secrets.GEMFURY_PUSH_TOKEN }}
        run: |
          conda install -y twine
          pipx run twine upload dist/* --repository-url "https://push.fury.io/balbasty/" -u "${TOKEN}" -p ""
